/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-29 14:08:19 UTC)
 * on 2013-05-02 at 18:32:36 UTC 
 * Modify at your own risk.
 */

package stephen.woods.bscproject.clubendpoint;

/**
 * Service definition for Clubendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ClubendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Clubendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://xz-gold-vault-8.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "clubendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Clubendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Clubendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getClub".
   *
   * This request holds the parameters needed by the the clubendpoint server.  After setting any
   * optional parameters, call the {@link GetClub#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetClub getClub(java.lang.Long id) throws java.io.IOException {
    GetClub result = new GetClub(id);
    initialize(result);
    return result;
  }

  public class GetClub extends ClubendpointRequest<stephen.woods.bscproject.clubendpoint.model.Club> {

    private static final String REST_PATH = "club/{id}";

    /**
     * Create a request for the method "getClub".
     *
     * This request holds the parameters needed by the the clubendpoint server.  After setting any
     * optional parameters, call the {@link GetClub#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetClub#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetClub(java.lang.Long id) {
      super(Clubendpoint.this, "GET", REST_PATH, null, stephen.woods.bscproject.clubendpoint.model.Club.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetClub setAlt(java.lang.String alt) {
      return (GetClub) super.setAlt(alt);
    }

    @Override
    public GetClub setFields(java.lang.String fields) {
      return (GetClub) super.setFields(fields);
    }

    @Override
    public GetClub setKey(java.lang.String key) {
      return (GetClub) super.setKey(key);
    }

    @Override
    public GetClub setOauthToken(java.lang.String oauthToken) {
      return (GetClub) super.setOauthToken(oauthToken);
    }

    @Override
    public GetClub setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetClub) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetClub setQuotaUser(java.lang.String quotaUser) {
      return (GetClub) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetClub setUserIp(java.lang.String userIp) {
      return (GetClub) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetClub setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetClub set(String parameterName, Object value) {
      return (GetClub) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertClub".
   *
   * This request holds the parameters needed by the the clubendpoint server.  After setting any
   * optional parameters, call the {@link InsertClub#execute()} method to invoke the remote operation.
   *
   * @param content the {@link stephen.woods.bscproject.clubendpoint.model.Club}
   * @return the request
   */
  public InsertClub insertClub(stephen.woods.bscproject.clubendpoint.model.Club content) throws java.io.IOException {
    InsertClub result = new InsertClub(content);
    initialize(result);
    return result;
  }

  public class InsertClub extends ClubendpointRequest<stephen.woods.bscproject.clubendpoint.model.Club> {

    private static final String REST_PATH = "club";

    /**
     * Create a request for the method "insertClub".
     *
     * This request holds the parameters needed by the the clubendpoint server.  After setting any
     * optional parameters, call the {@link InsertClub#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertClub#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link stephen.woods.bscproject.clubendpoint.model.Club}
     * @since 1.13
     */
    protected InsertClub(stephen.woods.bscproject.clubendpoint.model.Club content) {
      super(Clubendpoint.this, "POST", REST_PATH, content, stephen.woods.bscproject.clubendpoint.model.Club.class);
    }

    @Override
    public InsertClub setAlt(java.lang.String alt) {
      return (InsertClub) super.setAlt(alt);
    }

    @Override
    public InsertClub setFields(java.lang.String fields) {
      return (InsertClub) super.setFields(fields);
    }

    @Override
    public InsertClub setKey(java.lang.String key) {
      return (InsertClub) super.setKey(key);
    }

    @Override
    public InsertClub setOauthToken(java.lang.String oauthToken) {
      return (InsertClub) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertClub setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertClub) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertClub setQuotaUser(java.lang.String quotaUser) {
      return (InsertClub) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertClub setUserIp(java.lang.String userIp) {
      return (InsertClub) super.setUserIp(userIp);
    }

    @Override
    public InsertClub set(String parameterName, Object value) {
      return (InsertClub) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listClub".
   *
   * This request holds the parameters needed by the the clubendpoint server.  After setting any
   * optional parameters, call the {@link ListClub#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListClub listClub() throws java.io.IOException {
    ListClub result = new ListClub();
    initialize(result);
    return result;
  }

  public class ListClub extends ClubendpointRequest<stephen.woods.bscproject.clubendpoint.model.CollectionResponseClub> {

    private static final String REST_PATH = "club";

    /**
     * Create a request for the method "listClub".
     *
     * This request holds the parameters needed by the the clubendpoint server.  After setting any
     * optional parameters, call the {@link ListClub#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListClub#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListClub() {
      super(Clubendpoint.this, "GET", REST_PATH, null, stephen.woods.bscproject.clubendpoint.model.CollectionResponseClub.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListClub setAlt(java.lang.String alt) {
      return (ListClub) super.setAlt(alt);
    }

    @Override
    public ListClub setFields(java.lang.String fields) {
      return (ListClub) super.setFields(fields);
    }

    @Override
    public ListClub setKey(java.lang.String key) {
      return (ListClub) super.setKey(key);
    }

    @Override
    public ListClub setOauthToken(java.lang.String oauthToken) {
      return (ListClub) super.setOauthToken(oauthToken);
    }

    @Override
    public ListClub setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListClub) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListClub setQuotaUser(java.lang.String quotaUser) {
      return (ListClub) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListClub setUserIp(java.lang.String userIp) {
      return (ListClub) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListClub setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListClub setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListClub set(String parameterName, Object value) {
      return (ListClub) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeClub".
   *
   * This request holds the parameters needed by the the clubendpoint server.  After setting any
   * optional parameters, call the {@link RemoveClub#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveClub removeClub(java.lang.Long id) throws java.io.IOException {
    RemoveClub result = new RemoveClub(id);
    initialize(result);
    return result;
  }

  public class RemoveClub extends ClubendpointRequest<stephen.woods.bscproject.clubendpoint.model.Club> {

    private static final String REST_PATH = "club/{id}";

    /**
     * Create a request for the method "removeClub".
     *
     * This request holds the parameters needed by the the clubendpoint server.  After setting any
     * optional parameters, call the {@link RemoveClub#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveClub#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveClub(java.lang.Long id) {
      super(Clubendpoint.this, "DELETE", REST_PATH, null, stephen.woods.bscproject.clubendpoint.model.Club.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveClub setAlt(java.lang.String alt) {
      return (RemoveClub) super.setAlt(alt);
    }

    @Override
    public RemoveClub setFields(java.lang.String fields) {
      return (RemoveClub) super.setFields(fields);
    }

    @Override
    public RemoveClub setKey(java.lang.String key) {
      return (RemoveClub) super.setKey(key);
    }

    @Override
    public RemoveClub setOauthToken(java.lang.String oauthToken) {
      return (RemoveClub) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveClub setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveClub) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveClub setQuotaUser(java.lang.String quotaUser) {
      return (RemoveClub) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveClub setUserIp(java.lang.String userIp) {
      return (RemoveClub) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveClub setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveClub set(String parameterName, Object value) {
      return (RemoveClub) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateClub".
   *
   * This request holds the parameters needed by the the clubendpoint server.  After setting any
   * optional parameters, call the {@link UpdateClub#execute()} method to invoke the remote operation.
   *
   * @param content the {@link stephen.woods.bscproject.clubendpoint.model.Club}
   * @return the request
   */
  public UpdateClub updateClub(stephen.woods.bscproject.clubendpoint.model.Club content) throws java.io.IOException {
    UpdateClub result = new UpdateClub(content);
    initialize(result);
    return result;
  }

  public class UpdateClub extends ClubendpointRequest<stephen.woods.bscproject.clubendpoint.model.Club> {

    private static final String REST_PATH = "club";

    /**
     * Create a request for the method "updateClub".
     *
     * This request holds the parameters needed by the the clubendpoint server.  After setting any
     * optional parameters, call the {@link UpdateClub#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateClub#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link stephen.woods.bscproject.clubendpoint.model.Club}
     * @since 1.13
     */
    protected UpdateClub(stephen.woods.bscproject.clubendpoint.model.Club content) {
      super(Clubendpoint.this, "PUT", REST_PATH, content, stephen.woods.bscproject.clubendpoint.model.Club.class);
    }

    @Override
    public UpdateClub setAlt(java.lang.String alt) {
      return (UpdateClub) super.setAlt(alt);
    }

    @Override
    public UpdateClub setFields(java.lang.String fields) {
      return (UpdateClub) super.setFields(fields);
    }

    @Override
    public UpdateClub setKey(java.lang.String key) {
      return (UpdateClub) super.setKey(key);
    }

    @Override
    public UpdateClub setOauthToken(java.lang.String oauthToken) {
      return (UpdateClub) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateClub setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateClub) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateClub setQuotaUser(java.lang.String quotaUser) {
      return (UpdateClub) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateClub setUserIp(java.lang.String userIp) {
      return (UpdateClub) super.setUserIp(userIp);
    }

    @Override
    public UpdateClub set(String parameterName, Object value) {
      return (UpdateClub) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Clubendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Clubendpoint}. */
    @Override
    public Clubendpoint build() {
      return new Clubendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ClubendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setClubendpointRequestInitializer(
        ClubendpointRequestInitializer clubendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(clubendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
